apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 34.4.0
    helm:
      values: |
        service:
          spec:
            loadBalancerIP: 192.168.30.120
        ports:
          web:
            redirectTo:
              port: websecure
        logs:
          general:
            level: INFO
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
